%% segmentation routine using CAT12
% mbatch = matlab batch number (num)
% image = image filename to segment (char)
% tpm = tissue probability map for initial SPM seg step (char)
% cat_template = mni template for shooting registration (char)
% acc = cat processing accuracy (num; usually 0.5 for default or 0.75 for higher accuracy)
% surf = output surface? 0 = no, 1 = yes, 5 = for visual preview only?
function SPREAD_segmentation_routine(mbatch, image, tpm, cat_template, acc)
matlabbatch{mbatch}.spm.tools.cat.estwrite.data = {image};
matlabbatch{mbatch}.spm.tools.cat.estwrite.data_wmh = {''};
matlabbatch{mbatch}.spm.tools.cat.estwrite.nproc = 12;
matlabbatch{mbatch}.spm.tools.cat.estwrite.useprior = '';
matlabbatch{mbatch}.spm.tools.cat.estwrite.opts.tpm = {tpm};
matlabbatch{mbatch}.spm.tools.cat.estwrite.opts.affreg = 'mni';
matlabbatch{mbatch}.spm.tools.cat.estwrite.opts.biasstr = 0.5;
matlabbatch{mbatch}.spm.tools.cat.estwrite.opts.accstr = acc;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.restypes.best = [1 0.3];
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.setCOM = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.APP = 1070;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.affmod = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.NCstr = -Inf;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.LASstr = 0.5;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.LASmyostr = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.gcutstr = 2;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.cleanupstr = 0.5;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.BVCstr = 0.5;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.WMHC = 2;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.SLC = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.mrf = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.WMHtpm = {'C:\Users\SchmitzLab\Documents\spm12\toolbox\cat12\templates_MNI152NLin2009cAsym\cat_wmh_miccai2017.nii'};
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.BVtpm = {'C:\Users\SchmitzLab\Documents\spm12\toolbox\cat12\templates_MNI152NLin2009cAsym\cat_bloodvessels.nii'};
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.segmentation.SLtpm = {'C:\Users\SchmitzLab\Documents\spm12\toolbox\cat12\templates_MNI152NLin2009cAsym\cat_strokelesions_ATLAS303.nii'};
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.registration.regmethod.shooting.shootingtpm = {cat_template};
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.registration.regmethod.shooting.regstr = 0.5;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.registration.vox = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.registration.bb = 12;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.surface.pbtres = 0.5;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.surface.pbtmethod = 'pbtsimple';
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.surface.SRP = 22;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.surface.reduce_mesh = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.surface.vdist = 2;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.surface.scale_cortex = 0.7;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.surface.add_parahipp = 0.1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.surface.close_parahipp = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.admin.experimental = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.admin.new_release = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.admin.lazy = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.admin.ignoreErrors = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.admin.verb = 2;
matlabbatch{mbatch}.spm.tools.cat.estwrite.extopts.admin.print = 2;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.BIDS.BIDSno = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.surface = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.surf_measures = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.ROImenu.noROI = struct([]);
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.GM.native = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.GM.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.GM.mod = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.GM.dartel = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.WM.native = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.WM.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.WM.mod = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.WM.dartel = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.CSF.native = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.CSF.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.CSF.mod = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.CSF.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.ct.native = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.ct.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.ct.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.pp.native = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.pp.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.pp.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.WMH.native = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.WMH.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.WMH.mod = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.WMH.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.SL.native = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.SL.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.SL.mod = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.SL.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.TPMC.native = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.TPMC.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.TPMC.mod = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.TPMC.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.atlas.native = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.label.native = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.label.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.label.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.labelnative = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.bias.native = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.bias.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.bias.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.las.native = 1;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.las.warped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.las.dartel = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.jacobianwarped = 0;
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.warps = [1 0];
matlabbatch{mbatch}.spm.tools.cat.estwrite.output.rmat = 0;
spm_jobman('run',matlabbatch(mbatch))  
end
